-- Generated by datasets/scripts/build-migration.js -- do not edit by hand.
-- Source: datasets/runbooks/*.md  (1 entries)
--
-- INSERT OR REPLACE keyed on slug, so re-running an updated runbook edits the
-- existing row rather than creating a duplicate.

INSERT OR REPLACE INTO runbooks (
  slug, category, error_code, title, summary, root_cause,
  diagnostic_command, solution_steps, tags, source_url, verified_at
) VALUES
  (
    'k8s-pod-oom-killed',
    'kubernetes',
    'OOMKilled',
    'Pod terminated with OOMKilled (exit code 137)',
    'The kernel killed the container because it exceeded the memory limit set in
`resources.limits.memory`, or because the node itself ran out of memory. The pod
shows a `lastState.terminated.reason` of `OOMKilled` and an exit code of 137.',
    'When a cgroup reaches its hard memory limit, the Linux OOM killer sends SIGKILL
to the offending process. SIGKILL is signal 9, and a process terminated by a
signal reports `128 + signal`, which is where 137 comes from. The container is
killed outright, so there is no graceful shutdown and no application-level error
to find in the logs.

Two distinct cases produce the same exit code: the container exceeded its own
limit, or the node came under memory pressure and the kubelet evicted it. The
first shows `OOMKilled` on the container; the second shows an `Evicted` pod
status.',
    'kubectl get pod <pod-name> -n <namespace> -o jsonpath=''{.status.containerStatuses[*].lastState.terminated.reason}''',
    '[{"step":1,"action":"Confirm the kernel killed it rather than the app exiting","command":"kubectl describe pod <pod-name> -n <namespace> | grep -E \"Reason|Exit Code|Limits|Requests\"","expected":"Reason is OOMKilled and Exit Code is 137. If the reason is Error, this is not an OOM problem."},{"step":2,"action":"Check what the container was actually using","command":"kubectl top pod <pod-name> -n <namespace> --containers","expected":"Memory near the configured limit. A steady climb across restarts points to a leak rather than an undersized limit."},{"step":3,"action":"Check whether the node was under pressure","command":"kubectl describe node <node-name> | grep -A 5 \"Conditions:\"","expected":"MemoryPressure is False. If it is True, the node is the problem and the pod is a symptom."},{"step":4,"action":"Give the runtime headroom inside the limit","command":"kubectl set env deployment/<deployment-name> NODE_OPTIONS=\"--max-old-space-size=1536\"","expected":"Heap ceiling sits around 75% of the container limit, leaving room for non-heap memory."},{"step":5,"action":"Raise the limit once you know the real ceiling","command":"kubectl set resources deployment/<deployment-name> --limits=memory=2Gi --requests=memory=1Gi","expected":"Pod restarts and stays Running. Setting requests below limits lets the scheduler pack nodes without over-committing."}]',
    '["kubernetes","oom","cgroups","memory","limits","sigkill","137"]',
    'https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/',
    '2026-08-26'
  );
