-- Generated by datasets/scripts/build-migration.js -- do not edit by hand.
-- Source: datasets/runbooks/*.md  (5 entries)
--
-- INSERT OR REPLACE keyed on slug, so re-running an updated runbook edits the
-- existing row rather than creating a duplicate.

INSERT OR REPLACE INTO runbooks (
  slug, category, error_code, title, summary, root_cause,
  diagnostic_command, solution_steps, tags, source_url, verified_at
) VALUES
  (
    'dns-servfail-resolution-failure',
    'networking',
    'SERVFAIL',
    'DNS query returns SERVFAIL',
    'The resolver tried to answer and could not. Unlike `NXDOMAIN`, which is a
definitive "this name does not exist", `SERVFAIL` means the resolution process
itself broke — so the name may well be fine and something between you and the
authoritative servers is not.',
    'A recursive resolver returns SERVFAIL when it cannot produce a trustworthy
answer. The usual causes are a DNSSEC validation failure, authoritative
nameservers that are unreachable or timing out, or a broken delegation where the
parent zone points at nameservers that do not serve the zone.

The distinction from NXDOMAIN matters for triage. NXDOMAIN is an answer and
means fix the name. SERVFAIL is the absence of one and means fix the
infrastructure — often somebody else''s.',
    'dig +trace <domain> A',
    '[{"step":1,"action":"Confirm the status and rule out one bad resolver","command":"dig <domain> A @1.1.1.1 +noall +comments","expected":"status: NOERROR. If this returns SERVFAIL too, the problem is upstream and not with your resolver."},{"step":2,"action":"Walk the delegation from the root","command":"dig +trace <domain> A","expected":"A clean walk from root to TLD to the zone''s nameservers. The last level that responds is the last one working."},{"step":3,"action":"Test whether DNSSEC validation is the cause","command":"dig <domain> A @1.1.1.1 +cd +noall +comments","expected":"If +cd (checking disabled) returns NOERROR while the normal query returns SERVFAIL, this is a DNSSEC validation failure, usually a stale DS record after a key rollover."},{"step":4,"action":"Query the authoritative nameservers directly","command":"dig <domain> NS +short","expected":"The zone''s nameservers. Query the domain against each one in turn; a server that times out or refuses is the one to chase."},{"step":5,"action":"Check the parent''s delegation matches the zone","command":"dig <domain> NS @$(dig <tld> NS +short | head -1)","expected":"The same nameserver set the zone itself reports. Any difference is a stale delegation at the registrar."}]',
    '["dns","servfail","dnssec","resolver","dig","nxdomain","delegation"]',
    'https://www.rfc-editor.org/rfc/rfc9499.html',
    '2026-08-26'
  ),
  (
    'docker-port-is-already-allocated',
    'docker',
    'port is already allocated',
    'Bind for 0.0.0.0:PORT failed - port is already allocated',
    'Docker cannot publish a container port because something on the host is already
listening on it. The container never starts, and `docker ps` shows nothing new.',
    'Publishing a port makes the Docker daemon bind it on the host. If any process
already holds that host port the bind fails, and the daemon reports the whole
container start as failed.

The awkward case is when the holder is a stopped-but-not-removed container.
Docker keeps the port reservation for containers in the `created` or `exited`
state that were started with a published port, so `docker ps` looks clean while
`docker ps -a` shows the culprit.',
    'docker ps -a --filter "publish=<port>" --format "{{.ID}}\t{{.Status}}\t{{.Names}}"',
    '[{"step":1,"action":"Check whether a container is holding the port","command":"docker ps -a --filter \"publish=<port>\" --format \"{{.ID}}\\t{{.Status}}\\t{{.Names}}\"","expected":"Any container listed here holds the reservation, including ones with an Exited status."},{"step":2,"action":"If no container matches, find the host process","command":"sudo ss -tulpn | grep :<port>","expected":"The listening PID and program name. A dockerd or docker-proxy entry means Docker still owns it; anything else is a host service."},{"step":3,"action":"Remove the stale container","command":"docker rm -f <container-id>","expected":"The container ID echoed back. Re-run the diagnostic and the port should now be free."},{"step":4,"action":"If it is a host service, pick a different host port","command":"docker run -p 8081:8080 <image>","expected":"The container starts. The left number is the host port and the right is the container port, so only the host side moved."},{"step":5,"action":"For Compose, recreate rather than restart","command":"docker compose down --remove-orphans && docker compose up -d","expected":"Services come up cleanly. --remove-orphans clears containers left behind by a previous compose file."}]',
    '["docker","port","bind","eaddrinuse","compose","publish"]',
    'https://docs.docker.com/engine/network/',
    '2026-08-26'
  ),
  (
    'k8s-pod-oom-killed',
    'kubernetes',
    'OOMKilled',
    'Pod terminated with OOMKilled (exit code 137)',
    'The kernel killed the container because it exceeded the memory limit set in
`resources.limits.memory`, or because the node itself ran out of memory. The pod
shows a `lastState.terminated.reason` of `OOMKilled` and an exit code of 137.',
    'When a cgroup reaches its hard memory limit, the Linux OOM killer sends SIGKILL
to the offending process. SIGKILL is signal 9, and a process terminated by a
signal reports `128 + signal`, which is where 137 comes from. The container is
killed outright, so there is no graceful shutdown and no application-level error
to find in the logs.

Two distinct cases produce the same exit code: the container exceeded its own
limit, or the node came under memory pressure and the kubelet evicted it. The
first shows `OOMKilled` on the container; the second shows an `Evicted` pod
status.',
    'kubectl get pod <pod-name> -n <namespace> -o jsonpath=''{.status.containerStatuses[*].lastState.terminated.reason}''',
    '[{"step":1,"action":"Confirm the kernel killed it rather than the app exiting","command":"kubectl describe pod <pod-name> -n <namespace> | grep -E \"Reason|Exit Code|Limits|Requests\"","expected":"Reason is OOMKilled and Exit Code is 137. If the reason is Error, this is not an OOM problem."},{"step":2,"action":"Check what the container was actually using","command":"kubectl top pod <pod-name> -n <namespace> --containers","expected":"Memory near the configured limit. A steady climb across restarts points to a leak rather than an undersized limit."},{"step":3,"action":"Check whether the node was under pressure","command":"kubectl describe node <node-name> | grep -A 5 \"Conditions:\"","expected":"MemoryPressure is False. If it is True, the node is the problem and the pod is a symptom."},{"step":4,"action":"Give the runtime headroom inside the limit","command":"kubectl set env deployment/<deployment-name> NODE_OPTIONS=\"--max-old-space-size=1536\"","expected":"Heap ceiling sits around 75% of the container limit, leaving room for non-heap memory."},{"step":5,"action":"Raise the limit once you know the real ceiling","command":"kubectl set resources deployment/<deployment-name> --limits=memory=2Gi --requests=memory=1Gi","expected":"Pod restarts and stays Running. Setting requests below limits lets the scheduler pack nodes without over-committing."}]',
    '["kubernetes","oom","cgroups","memory","limits","sigkill","137"]',
    'https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/',
    '2026-08-26'
  ),
  (
    'linux-emfile-too-many-open-files',
    'linux',
    'EMFILE',
    'Too many open files (EMFILE)',
    'A process hit its file-descriptor limit. Every new file, socket or pipe it tries
to open fails with `EMFILE`, so the symptom is usually a service that accepts no
new connections while the process itself keeps running.',
    'Each process has a limit on concurrently open descriptors, reported by
`ulimit -n` and enforced as `RLIMIT_NOFILE`. Sockets count, so a busy server or
one that leaks connections reaches the limit even with few actual files open.

Two things commonly get confused here. The soft limit is what applies and can be
raised by the process up to the hard limit. And a service started by systemd does
not inherit your shell''s limits at all — it gets whatever `LimitNOFILE` says in
its unit, which is why raising `ulimit -n` in a terminal appears to do nothing.',
    'cat /proc/$(pgrep -f <process-name> | head -1)/limits | grep -i "open files"',
    '[{"step":1,"action":"Read the limit the running process actually has","command":"cat /proc/<pid>/limits | grep -i \"open files\"","expected":"Soft and hard values. A soft limit of 1024 is the common default and is low for any network service."},{"step":2,"action":"Count what the process currently holds","command":"ls /proc/<pid>/fd | wc -l","expected":"A number close to the soft limit confirms exhaustion. Watch it over a minute: steadily climbing under constant load means a leak, not an undersized limit."},{"step":3,"action":"Find what kind of descriptor is being held","command":"ls -l /proc/<pid>/fd | awk ''{print $NF}'' | sed ''s/:.*//'' | sort | uniq -c | sort -rn | head","expected":"A dominant type. Large counts of socket entries usually mean connections are not being closed or pooled."},{"step":4,"action":"Raise the limit for a systemd service","command":"systemctl edit <service-name>","expected":"An override editor. Add LimitNOFILE=65535 under a [Service] section, then reload and restart the unit."},{"step":5,"action":"Apply the change and confirm it took","command":"systemctl daemon-reload && systemctl restart <service-name> && cat /proc/$(systemctl show -p MainPID --value <service-name>)/limits | grep -i \"open files\"","expected":"The new soft limit. If it still shows the old value, the override did not apply to the unit you restarted."}]',
    '["linux","emfile","ulimit","file descriptors","nofile","systemd","sockets"]',
    'https://man7.org/linux/man-pages/man2/open.2.html',
    '2026-08-26'
  ),
  (
    'tls-unable-to-get-local-issuer-certificate',
    'networking',
    'unable to get local issuer certificate',
    'TLS verification fails with unable to get local issuer certificate',
    'The client can reach the server and negotiate TLS, but cannot build a trust
chain from the presented certificate up to a CA it trusts. Browsers often work
while curl, Node or Python fail on the same URL.',
    'Verification needs the full chain: leaf, any intermediates, then a root the
client already trusts. Servers are supposed to send the leaf plus intermediates;
the root comes from the client''s trust store.

When a server is misconfigured to send only the leaf, browsers frequently paper
over it — they cache intermediates from previous sessions and can fetch missing
ones via the AIA extension. Most command-line clients do neither, which is why
the same endpoint works in Chrome and fails in curl. The other common cause is a
TLS-intercepting proxy presenting its own root that the client has never seen.',
    'openssl s_client -connect <host>:443 -servername <host> -showcerts < /dev/null',
    '[{"step":1,"action":"Look at how many certificates the server actually sends","command":"openssl s_client -connect <host>:443 -servername <host> -showcerts < /dev/null 2>/dev/null | grep -c \"BEGIN CERTIFICATE\"","expected":"Two or more for a normal chain. Exactly one means the server is sending only the leaf and is misconfigured."},{"step":2,"action":"Read the verify result and the chain order","command":"openssl s_client -connect <host>:443 -servername <host> < /dev/null 2>/dev/null | grep -E \"Verify return code|^ *[0-9] s:|^ *[0-9] i:\"","expected":"Verify return code 0 (ok) when healthy. Code 20 is the unable-to-get-local-issuer case; each s:/i: pair shows a subject and its issuer."},{"step":3,"action":"Check whether a proxy is intercepting","command":"openssl s_client -connect <host>:443 -servername <host> < /dev/null 2>/dev/null | grep \"issuer=\"","expected":"A public CA. A company or appliance name means traffic is being intercepted, and that CA has to be added to the client''s trust store."},{"step":4,"action":"Confirm the client is reading the trust store you think it is","command":"curl -sSv https://<host> 2>&1 | grep -iE \"CAfile|CApath\"","expected":"A path to a CA bundle. Node uses its own bundled roots unless NODE_EXTRA_CA_CERTS is set; Python requests uses certifi''s."},{"step":5,"action":"Fix the server rather than the clients where you can","command":"cat leaf.crt intermediate.crt > fullchain.crt","expected":"A bundle with the leaf first and intermediates after. Point the server at this file, reload, and re-run step 1 to confirm the count went up."}]',
    '["tls","ssl","certificate","ca","openssl","curl","chain","intermediate"]',
    'https://curl.se/docs/sslcerts.html',
    '2026-08-26'
  );
